version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ticket_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
    container_name: ticket_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ticketdb
      JWT_SECRET: supersecret
    ports:
      - "5000:5000"

volumes:
  postgres_data: